version: 0.2

env:
  variables:
    IMAGE_TAG: v1.2   # Set or dynamically replace this version tag (e.g., v1.2 or from Git commit)

  secrets-manager:
    # DockerHub credentials
    DOCKERHUB_USERNAME: cribr-dockerhub-username
    DOCKERHUB_PASSWORD: cribr-dockerhub-password

    # Supabase keys
    SUPABASE_SERVICE_KEY: cribr-supabase-service-key

    # Terraform user credentials
    AWS_ACCESS_KEY_ID: cribr-terraform-user-access-key
    AWS_SECRET_ACCESS_KEY: cribr-terraform-user-secret-key

phases:
  install:
    commands:
      - echo "Ensuring Docker is available..."
      - docker --version
      - echo "Installing kubectl if not present..."
        if ! command -v kubectl &> /dev/null; then
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl /usr/local/bin/
        fi
      - kubectl version --client

  pre_build:
    commands:
      - echo "Verifying DockerHub credentials..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 493834426110.dkr.ecr.us-east-1.amazonaws.com
      - echo "Terraform user credentials are available via AWS CLI"
      - aws sts get-caller-identity

  build:
    commands:
      - echo "Logging in to Amazon ECR again before push to ensure valid credentials..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 493834426110.dkr.ecr.us-east-1.amazonaws.com

      - echo "Building Docker image..."
      - docker build --build-arg SUPABASE_SERVICE_KEY="$SUPABASE_SERVICE_KEY" -t cribr-app .

      - echo "Tagging Docker image for ECR with version $IMAGE_TAG..."
      - docker tag cribr-app:latest 493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo:$IMAGE_TAG

      - echo "Pushing Docker image to ECR..."
      - docker push 493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo:$IMAGE_TAG

  post_build:
    commands:
      - echo "Updating Kubernetes deployment..."
      - aws eks --region us-east-1 update-kubeconfig --name cribr-cluster

      # Update deployment.yaml with new versioned image and enforce Always pull policy
      - |
        sed -i "s|image: .*|image: 493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo:$IMAGE_TAG|g" cribr-cicd/deployment.yaml
      - |
        sed -i "s|imagePullPolicy: .*|imagePullPolicy: Always|g" cribr-cicd/deployment.yaml

      - echo "Applying updated deployment..."
      - kubectl apply -f cribr-cicd/deployment.yaml -n cribr-ns

      - echo "Waiting for rollout to complete..."
      - kubectl rollout status -n cribr-ns deployment/cribr-app

      - echo "Deployment complete."

artifacts:
  files:
    - '**/*'
