version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: cribr-dockerhub-credentials:DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD: cribr-dockerhub-credentials:DOCKERHUB_PASSWORD

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 493834426110.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t cribr-app .
      - echo Tagging Docker image for ECR...
      - docker tag cribr-app:latest 493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo:latest
      - echo Updating Kubernetes deployment...
      - kubectl set image -n cribr-ns deployment/cribr-app cribr-container=493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo:latest
      - kubectl apply -f cribr-cicd/deployment.yaml
      - echo Deployment complete.

artifacts:
  files:
    - '**/*'
