

version: 0.2

env:
  variables:
    ECR_REPO_URI: 493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo
    K8S_NAMESPACE: cribr-ns
    DEPLOYMENT_YAML: cribr-cicd/deployment.yaml

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo Logging in to ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_URI
      - echo Setting IMAGE_TAG variable
      - IMAGE_TAG=latest
      - echo Setting up kubectl...
      - aws eks --region us-east-1 update-kubeconfig --name cribr-eks-cluster

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - echo Docker image built successfully

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo Updating Kubernetes deployment...
      - kubectl set image -n $K8S_NAMESPACE deployment/cribr-app cribr-container=$ECR_REPO_URI:$IMAGE_TAG
      - kubectl apply -f $DEPLOYMENT_YAML
      - echo Deployment complete.

artifacts:
  files:
    - '**/*'
