# cribr-cicd\deployment.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cribr-ns
  name: cribr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cribr-app
  template:
    metadata:
      labels:
        app: cribr-app
    spec:
      # Disable automounting of service account token (safer) OR you could bind to RBAC if needed
      automountServiceAccountToken: false
      containers:
        - name: cribr-container
          image: 493834426110.dkr.ecr.us-east-1.amazonaws.com/cribr-app-repo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: cribr-secrets
          resources:
            requests:
              cpu: "250m"        # CPU request
              memory: "256Mi"    # Memory request
              ephemeral-storage: "512Mi"  # Ephemeral storage request
            limits:
              memory: "512Mi"    # Memory limit
              ephemeral-storage: "1Gi"    # Ephemeral storage limit
          volumeMounts:
            - name: cribr-storage
              mountPath: /data   # Example storage mount path
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: cribr-storage
          persistentVolumeClaim:
            claimName: cribr-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cribr-pvc
  namespace: cribr-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   # Storage request
